# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('nationality', models.CharField(max_length=150)),
                ('alias', models.CharField(max_length=100)),
            ],
        ),
    ]
